[project]
name = "django-rest-framework-homework"
version = "0.1.0"
package-mode = false
description = ""
authors = [
    {name = "Dmitry globa", email = "dima.globa2015@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.14"

dependencies = [
    "django (>=6.0.5,<7.0.0)",
    "djangorestframework (>=3.17.1,<4.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)",
    "asgiref (>=3.12.1,<4.0.0)",
    "ast-serialize (>=0.6.0,<0.7.0)",
    "coverage (>=7.15.2,<8.0.0)",
    "django-stubs (>=6.0.7,<7.0.0)",
    "django-stubs-ext (>=6.0.7,<7.0.0)",
    "djangorestframework-stubs (>=3.17.0,<4.0.0)",
    "drf-yasg (>=1.21.15,<2.0.0)",
    "inflection (>=0.5.1,<0.6.0)",
    "iniconfig (>=2.3.0,<3.0.0)",
    "librt (>=0.13.0,<0.14.0)",
    "mypy (>=2.3.0,<3.0.0)",
    "mypy-extensions (>=1.1.0,<2.0.0)",
    "packaging (>=26.2,<27.0)",
    "pathspec (>=1.1.1,<2.0.0)",
    "pillow (>=12.3.0,<13.0.0)",
    "pluggy (>=1.6.0,<2.0.0)",
    "pygments (>=2.20.0,<3.0.0)",
    "pyjwt (>=2.13.0,<3.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "pytz (>=2026.3.post1,<2027.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "ruff (>=0.16.0,<0.17.0)",
    "sqlparse (>=0.5.5,<0.6.0)",
    "types-pyyaml (>=6.0.12.20260724,<7.0.0.0)",
    "typing-extensions (>=4.16.0,<5.0.0)",
    "uritemplate (>=4.2.0,<5.0.0)",
    "django-cors-headers (>=4.9.0,<5.0.0)",
    "requests (>=2.34.2,<3.0.0)",
    "celery (>=5.6.3,<6.0.0)",
    "redis (>=8.1.0,<9.0.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "mypy>=1.10.0",
    "django-stubs>=5.0.0",
    "djangorestframework-stubs>=3.15.0",
    "ruff>=0.4.0",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "pytest (>=9.1.1,<10.0.0)"
]

[tool.mypy]
# Подключаем плагины типизации для Django и DRF
plugins = [
    "mypy_django_plugin.main",
    "mypy_drf_plugin.main"
]

# Базовые настройки строгости проверки типов
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
check_untyped_defs = true

# Пропускаем проверку сторонних библиотек без аннотаций типов
ignore_missing_imports = true

[tool.django-stubs]
# Указываем mypy, где искать конфигурацию Django
django_settings_module = "config.settings"

[tool.ruff]
# Целевая версия Python
target-version = "py312"
line-length = 88

[tool.ruff.lint]
# Какие правила проверять: 
# E, F — базовые ошибки и стиль (Pyflakes/pycodestyle)
# I — сортировка импортов (isort)
# N — именование переменных (pep8-naming)
# DJ — специфичные правила для Django
select = ["E", "F", "I", "N", "DJ"]
ignore = []

[tool.ruff.format]
# Настройки форматирования текста
quote-style = "double"
indent-style = "space"
